spring:
  application:
    name: api-gateway
  jackson:
    default-property-inclusion: NON_NULL
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8003

eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:${random.uuid}

jwt:
  secret: iniadalahpengecohhandalyangsangatsulitdipecahkanhehe
  expiration-time: 3600000